package com.dam.gs.appentradas.core.constants

object AppConstants {
    const val DB_NAME = "edu-eventum1"
    const val URL_ODOO = "https://edu-eventum1.odoo.com/"
    const val FIELD_BARCODE = "barcode"
    const val FIELD_EVENT_ID = "event_id"
    const val FIELD_ID = "id"
    const val FIELD_IMAGE = "image_1024"
    const val FIELD_NAME = "name"
    const val FIELD_PARTNER_ID = "partner_id"
    const val FIELD_STAGE_ID_NAME = "stage_id.name"
    const val FIELD_STATE = "state"
    const val FIELDS = "fields"
    const val EMPTY_STRING = ""
    const val IDIOMA_EN = "en"
    const val IDIOMA_ES = "es"
    const val LIMIT = "limit"
    const val LIMIT_ONE = 1
    const val METHOD_AUTHENTICATE = "authenticate"
    const val METHOD_EXECUTE_KW = "execute_kw"
    const val METHOD_SEARCH_READ = "search_read"
    const val METHOD_SET_DONE = "action_set_done"
    const val MODEL_EVENTO = "event.event"
    const val MODEL_REGISTRO = "event.registration"
    const val OPERATOR_EQUALS = "="

    const val PREFS_NAME = "ajustes"
    const val PREF_IDIOMA = "idioma"
    const val PREF_IDIOMA_DEFAULT = "es"
    const val PREF_TEMA = "tema"
    const val PREF_ULTIMO_USUARIO = "ultimo_usuario"
    const val STAGE_ANUNCIADO = "Announced"
    const val STATE_CANCELLED = "cancel"
    const val STATE_DONE = "done"
    const val STATE_OPEN = "open"
    const val SIN_NOMBRE = "Sin nombre"
    const val XMLRPC_COMMON = "/xmlrpc/2/common"
    const val XMLRPC_OBJECT = "/xmlrpc/2/object"
}